# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='vague_date',
            field=models.BooleanField(default=False),
        ),
    ]
