# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=8, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Release')),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='position',
        ),
        migrations.RemoveField(
            model_name='track',
            name='release',
        ),
        migrations.AddField(
            model_name='releasetrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Track'),
        ),
        migrations.AddField(
            model_name='track',
            name='release',
            field=models.ManyToManyField(through='music.ReleaseTrack', to='music.Release'),
        ),
    ]
