# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20160228_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
