# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_release_catalog_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('long_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='artists',
            field=models.ManyToManyField(to='music.Artist'),
        ),
    ]
