# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20160316_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='_artist_credit',
            field=models.CharField(blank=True, help_text='Overrides artists', max_length=100),
        ),
    ]
