# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_release_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imported_images')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Release')),
            ],
        ),
    ]
