# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_release_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
