# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20160322_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='alpha_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
