# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_artist_alpha_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_artist', to='music.Artist')),
            ],
        ),
        migrations.AlterField(
            model_name='release',
            name='artists',
            field=models.ManyToManyField(related_name='release_artist', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='role',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_release', to='music.Release'),
        ),
        migrations.AddField(
            model_name='release',
            name='credits',
            field=models.ManyToManyField(through='music.Role', to='music.Artist'),
        ),
    ]
