# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20160323_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='tracks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
