# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_role_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='cover_notes',
            field=models.TextField(blank=True),
        ),
    ]
