# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 05:07
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_release_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ('-release_date',)},
        ),
        migrations.AlterField(
            model_name='release',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Release'),
        ),
    ]
