# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20160329_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
