# Generated by Django 4.0.3 on 2022-04-10 00:12

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0024_alter_artist_id_alter_image_id_alter_label_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
                ("frets", models.CharField(max_length=17)),
                ("fingers", models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name="track",
            name="soundcloud",
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.CreateModel(
            name="RecordingTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                ("instrument", models.CharField(max_length=255)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="music.artist"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.track"
                    ),
                ),
            ],
        ),
    ]
