# Generated by Django 4.0.3 on 2022-04-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0025_chord_alter_track_soundcloud_recordingtrack"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="discogs_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="release",
            name="discogs_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recordingtrack",
            name="order",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
