"""
Django settings for bhp project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os


# root settings conf. imports local settings and set DEBUG-related flags.
try:
    from local_settings import * #the first line of local_settings should be "from default_settings import *", then it can override those settings it sees fit.
except ImportError:
    from default_settings import *

